-- V12: car image metadata. The image bytes live in object storage
-- (local disk in dev, or S3/R2 in prod); this table is the source of truth for
-- WHICH images a car has, in WHAT order, and the storage key to fetch each.
--
-- A child table (not an images[] column on car) so each image carries its own
-- metadata, can be ordered/reordered via `position`, and deletes cleanly. The FK
-- cascades: dropping a car removes its image rows (the objects are cleaned up by
-- the application when images are deleted individually).
CREATE TABLE car_image (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_id       BIGINT       NOT NULL,
    object_key   VARCHAR(300) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    size_bytes   BIGINT       NOT NULL CHECK (size_bytes >= 0),
    position     INT          NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_car_image_car FOREIGN KEY (car_id) REFERENCES car (id) ON DELETE CASCADE,
    CONSTRAINT uq_car_image_key UNIQUE (object_key)
);

CREATE INDEX idx_car_image_car ON car_image (car_id);
