-- V13: private documents — KYC (user identity) and car insurance/registration
-- Unlike car images (public product photos, #36), these are
-- sensitive: the bytes live in object storage under a private key prefix and are
-- served ONLY through an authenticated, authorized endpoint — never the public
-- /api/media path, never a shareable presigned URL.
--
-- One generic table with a polymorphic owner: KYC docs are owned by a user, car
-- docs by a car. owner_id therefore has NO foreign key (it points at different
-- tables depending on owner_type); uploaded_by does FK to users. doc_type must
-- match owner_type (enforced in the service): KYC_* -> USER, INSURANCE/
-- REGISTRATION -> CAR.
CREATE TABLE document (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_type   VARCHAR(20)  NOT NULL CHECK (owner_type IN ('USER', 'CAR')),
    owner_id     BIGINT       NOT NULL,
    doc_type     VARCHAR(30)  NOT NULL
                  CHECK (doc_type IN ('KYC_IDENTITY', 'KYC_ADDRESS', 'INSURANCE', 'REGISTRATION')),
    object_key   VARCHAR(300) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    size_bytes   BIGINT       NOT NULL CHECK (size_bytes >= 0),
    status       VARCHAR(20)  NOT NULL DEFAULT 'PENDING'
                  CHECK (status IN ('PENDING', 'VERIFIED', 'REJECTED')),
    uploaded_by  BIGINT       NOT NULL,
    review_note  VARCHAR(500),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_document_uploader FOREIGN KEY (uploaded_by) REFERENCES users (id),
    CONSTRAINT uq_document_key UNIQUE (object_key)
);

CREATE INDEX idx_document_owner  ON document (owner_type, owner_id);
CREATE INDEX idx_document_status ON document (status);
