-- V14: reviews & ratings (Task #39). One review per booking, written by the
-- booking's customer after the rental is COMPLETED. car_id is denormalized off
-- the booking so the per-car rating aggregation (avg + count) is a single indexed
-- scan with no join — the "aggregation" lesson of this task.
CREATE TABLE review (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT      NOT NULL,
    car_id     BIGINT      NOT NULL,
    user_id    BIGINT      NOT NULL,
    rating     INTEGER     NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment    VARCHAR(2000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_review_booking FOREIGN KEY (booking_id) REFERENCES booking (id),
    CONSTRAINT fk_review_car     FOREIGN KEY (car_id)     REFERENCES car (id),
    CONSTRAINT fk_review_user    FOREIGN KEY (user_id)    REFERENCES users (id),
    -- one review per booking (also guards the create-twice race)
    CONSTRAINT uq_review_booking UNIQUE (booking_id)
);

CREATE INDEX idx_review_car ON review (car_id);
