-- V1: Core Phase-1 entities for the Car Rental Marketplace.
--   users          - people (customers, agency staff, admins)
--   agency         - tenants that own and rent out cars
--   agency_member  - which users belong to which agency, and their role
--   car            - the rentable inventory, owned by an agency
--
-- Conventions:
--   * snake_case names (Postgres convention; Hibernate maps CamelCase -> snake)
--   * enum-like columns are VARCHAR + CHECK, values UPPERCASE to match
--     Java enums persisted with @Enumerated(STRING)
--   * geo is stored as plain latitude/longitude for now; a real PostGIS
--     geometry column + GiST index arrives in Task #33 (geo search)
--   * booking/payment/review/notification come in their own later migrations

-- ── users ─────────────────────────────────────────────────────────────────
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(150) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    phone         VARCHAR(20),
    password_hash VARCHAR(255) NOT NULL,
    kyc_status    VARCHAR(20)  NOT NULL DEFAULT 'PENDING'
                   CHECK (kyc_status IN ('PENDING', 'VERIFIED', 'REJECTED')),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_email UNIQUE (email)
);

-- ── agency (tenant) ───────────────────────────────────────────────────────
CREATE TABLE agency (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(200) NOT NULL,
    owner_id        BIGINT       NOT NULL,
    city            VARCHAR(100),
    latitude        DOUBLE PRECISION,
    longitude       DOUBLE PRECISION,
    gst_no          VARCHAR(20),
    payout_account  VARCHAR(100),
    status          VARCHAR(20)  NOT NULL DEFAULT 'PENDING'
                     CHECK (status IN ('PENDING', 'ACTIVE', 'SUSPENDED')),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_agency_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE INDEX idx_agency_city ON agency (city);
CREATE INDEX idx_agency_owner ON agency (owner_id);

-- ── agency_member (RBAC: user <-> agency, with a role) ─────────────────────
CREATE TABLE agency_member (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    agency_id  BIGINT      NOT NULL,
    role       VARCHAR(20) NOT NULL
                CHECK (role IN ('ADMIN', 'STAFF')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_member_user   FOREIGN KEY (user_id)   REFERENCES users (id),
    CONSTRAINT fk_member_agency FOREIGN KEY (agency_id) REFERENCES agency (id),
    CONSTRAINT uq_member_user_agency UNIQUE (user_id, agency_id)
);

CREATE INDEX idx_member_agency ON agency_member (agency_id);

-- ── car (rentable inventory) ──────────────────────────────────────────────
CREATE TABLE car (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id     BIGINT        NOT NULL,
    make          VARCHAR(60)   NOT NULL,
    model         VARCHAR(60)   NOT NULL,
    category      VARCHAR(40)   NOT NULL,
    reg_no        VARCHAR(20)   NOT NULL,
    price_per_day NUMERIC(10,2) NOT NULL CHECK (price_per_day >= 0),
    latitude      DOUBLE PRECISION,
    longitude     DOUBLE PRECISION,
    status        VARCHAR(20)   NOT NULL DEFAULT 'AVAILABLE'
                   CHECK (status IN ('AVAILABLE', 'BOOKED', 'MAINTENANCE', 'OUT_OF_SERVICE')),
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT fk_car_agency FOREIGN KEY (agency_id) REFERENCES agency (id),
    CONSTRAINT uq_car_agency_regno UNIQUE (agency_id, reg_no)
);

CREATE INDEX idx_car_agency ON car (agency_id);
CREATE INDEX idx_car_category ON car (category);
CREATE INDEX idx_car_status ON car (status);
CREATE INDEX idx_car_price ON car (price_per_day);
