-- V3: the booking table + the anti-double-booking guarantee.
-- See docs/booking-engine-internals.md for the full explanation.

-- btree_gist lets a single GiST index mix scalar equality (car_id WITH =)
-- with range overlap (period WITH &&) — required by the exclusion constraint.
CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE booking (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_id          BIGINT      NOT NULL,
    user_id         BIGINT      NOT NULL,
    agency_id       BIGINT      NOT NULL,
    start_ts        TIMESTAMPTZ NOT NULL,
    end_ts          TIMESTAMPTZ NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'PENDING'
                     CHECK (status IN ('PENDING','CONFIRMED','ACTIVE','COMPLETED','CANCELLED','EXPIRED')),
    amount          NUMERIC(12,2),
    deposit         NUMERIC(12,2),
    expires_at      TIMESTAMPTZ,
    idempotency_key VARCHAR(80),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_booking_car    FOREIGN KEY (car_id)    REFERENCES car (id),
    CONSTRAINT fk_booking_user   FOREIGN KEY (user_id)   REFERENCES users (id),
    CONSTRAINT fk_booking_agency FOREIGN KEY (agency_id) REFERENCES agency (id),
    -- end must be strictly after start
    CONSTRAINT chk_booking_period CHECK (end_ts > start_ts),
    -- THE GUARANTEE: the same car can never have two overlapping bookings,
    -- among rows that are still "active". '[)' = inclusive start, exclusive end,
    -- so a car returned at 10:00 can be re-rented from 10:00 (back-to-back OK).
    CONSTRAINT no_overlap EXCLUDE USING gist (
        car_id WITH =,
        tstzrange(start_ts, end_ts, '[)') WITH &&
    ) WHERE (status IN ('PENDING','CONFIRMED','ACTIVE'))
);

CREATE INDEX idx_booking_car ON booking (car_id);
CREATE INDEX idx_booking_user ON booking (user_id);
CREATE INDEX idx_booking_agency ON booking (agency_id);
