-- V6: payments (Task #20). A payment order is created when the user proceeds to
-- pay for a PENDING booking; the provider (Razorpay, or a local mock in dev)
-- returns an order id we store as provider_ref. The webhook (#21) flips it to
-- CAPTURED and confirms the booking.
CREATE TABLE payment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id      BIGINT        NOT NULL,
    type            VARCHAR(20)   NOT NULL
                     CHECK (type IN ('BOOKING','DEPOSIT','REFUND','PAYOUT')),
    amount          NUMERIC(12,2) NOT NULL CHECK (amount >= 0),
    status          VARCHAR(20)   NOT NULL DEFAULT 'CREATED'
                     CHECK (status IN ('CREATED','CAPTURED','FAILED','REFUNDED')),
    provider        VARCHAR(20)   NOT NULL,
    provider_ref    VARCHAR(120),
    idempotency_key VARCHAR(80),
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT fk_payment_booking FOREIGN KEY (booking_id) REFERENCES booking (id)
);

CREATE INDEX idx_payment_booking ON payment (booking_id);
-- provider order/payment ids are unique; also the webhook looks payments up by it
CREATE UNIQUE INDEX uq_payment_provider_ref ON payment (provider_ref) WHERE provider_ref IS NOT NULL;
