-- V8: notifications (Task #28). One row per message sent to a user, written by
-- the notification consumer when it reacts to a domain event. The unique index
-- makes the consumer idempotent under Kafka's at-least-once delivery: a
-- re-delivered event won't create a duplicate notification.
CREATE TABLE notification (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL,
    booking_id  BIGINT,
    channel     VARCHAR(20) NOT NULL CHECK (channel IN ('EMAIL','PUSH')),
    type        VARCHAR(40) NOT NULL,    -- the domain event type that triggered it
    payload     TEXT,                    -- the rendered message
    status      VARCHAR(20) NOT NULL DEFAULT 'SENT' CHECK (status IN ('SENT','FAILED')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_notification_user ON notification (user_id);
-- Idempotency: at most one notification per (booking, type, channel).
CREATE UNIQUE INDEX uq_notification_dedup
    ON notification (booking_id, type, channel)
    WHERE booking_id IS NOT NULL;
