-- V9: append-only audit/analytics log. The analytics consumer writes
-- one row per domain event it receives — an independent record of "what
-- happened", separate from the notification consumer. event_id is unique so a
-- re-delivered event is recorded once (idempotent).
CREATE TABLE event_audit (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    VARCHAR(80),             -- dedup key (type + booking + occurred_at)
    type        VARCHAR(40) NOT NULL,
    booking_id  BIGINT,
    user_id     BIGINT,
    agency_id   BIGINT,
    amount      NUMERIC(12,2),
    occurred_at TIMESTAMPTZ,
    received_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_event_audit_type ON event_audit (type);
CREATE INDEX idx_event_audit_agency ON event_audit (agency_id);
CREATE UNIQUE INDEX uq_event_audit_event_id ON event_audit (event_id) WHERE event_id IS NOT NULL;
